# ------------------------------------------------------------------
# This is a basic workflow to help you get started with Actions
# Copyleft (c) by Inom Ikromov 2021

name: My-GitHubActions-Basics
env:
  APPLICATION_NAME    : "MyFlask"
  DEPLOY_PACKAGE_NAME :  "flask-deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
       - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      
      - name: Print Hello Message
        run: echo "Hello World from testing_job"
        
      - name: Extcute few commands
        run :  |
          echo "Hello Message1"
          echo "Hello Message2"
          echo "Applocation name: ${{ env.APPLICATION_NAME }}"
          
      - name: List current folder
        run : ls -la
        
      - name: Git clone my repo
        uses: actions/checkout@v1
        
      - name: List current folder
        run : ls -la
        


  my_deploy:
   runs-on: ubuntu-latest
   needs: [my_testing]
   env:
       VAR1 : "this is Job level Variable1"
       VAR2 : "This is Job level Variable2"
   
   steps:
      - name: Print Hello Message in Deploy
        run : echo "Hello World from Deploy job"
        
      - name: Print env vars from this Job
        run : |
           echo " Var1 = ${{ env.VAR1" }}
           echo " VAR2 = ${{ env.VAR2 "}}
 #          echo " VAR3 = $LOCAL_VAR"
 #       env:
 #          LOCAL_VAR: "This is Super Local Environment variable"
        
        
      - name: Printing Deployment package
        run : echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME}}"
        
      - name: Let's test some packages iof they are here 1
        run : aws --version
        
      - name: Let's test some packages iof they are here 2
        run : zip --version
        
      - name: Let's test some packages iof they are here 3
        run : gcloud --version
        
      
   
