# ------------------------------------------------------------------
# This is a basic workflow to help you get started with Actions
# Copyleft (c) by Inom Ikromov 2021

name: My-GitHubActions-Basics           

on:
  push:
    branches:
       - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      
      - name: Print Hello Message
        run: echo "Hello World from testing_job"


  my_deploy:
   runs-on: ubuntu-latest
   needs: [my_testing]
   
   steps:
      - name: Print Hello Message
        run : echo "Hello World from Deploy job"
   
